- name: Check if bootstrap is needed
  raw: stat $HOME/.ansible_bootstrapped
  register: need_bootstrap
  ignore_errors: True

- name: Run bootstrap3.sh
  script: bootstrap3.sh {{ (proxy | default(dict(https='')))['https'] }}
  when: need_bootstrap | failed

